### ISSUE TITLE
Script only supports TAXII 1.0, not 1.1

### ISSUE THREAD

**Issue by JasonKeirstead** [Soltra/cti-stats#2]
Having trouble running this script against our public TAXII API:

```
./cti-stats -u <user token> -p <password token> -e /taxii -h api.xforce.ibmcloud.com -c xfe.default  --taxii-stats

Traceback (most recent call last):
  File "./cti-stats", line 69, in <module>
    main()
  File "./cti-stats", line 63, in main
    args['--use-ssl'], args['--validate-cert'])
  File "/home/jasonk/cti-stats/lib/cti.py", line 101, in taxii_poll
    poll_request.message_id)
  File "/home/jasonk/cti-stats/python_env/local/lib/python2.7/site-packages/libtaxii/__init__.py", line 50, in get_message_from_http_response
    return get_message_from_urllib_addinfourl(http_response, in_response_to)
  File "/home/jasonk/cti-stats/python_env/local/lib/python2.7/site-packages/libtaxii/__init__.py", line 96, in get_message_from_urllib_addinfourl
    return tm11.get_message_from_xml(response_message)
  File "/home/jasonk/cti-stats/python_env/local/lib/python2.7/site-packages/libtaxii/messages_11.py", line 107, in get_message_from_xml
    return StatusMessage.from_etree(etree_xml)
  File "/home/jasonk/cti-stats/python_env/local/lib/python2.7/site-packages/libtaxii/messages_11.py", line 3090, in from_etree
    msg = super(StatusMessage, cls).from_etree(etree_xml, **kwargs)
  File "/home/jasonk/cti-stats/python_env/local/lib/python2.7/site-packages/libtaxii/messages_11.py", line 1120, in from_etree
    message_id = src_etree.xpath('/taxii_11:*/@message_id', namespaces=ns_map)[0]
IndexError: list index out of range
```

I dumped the response and it is returning the following

```
<taxii_11:Status_Message xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" status_type="BAD_MESSAGE">
  <taxii_11:Message>Unsupported X-TAXII-Content-Type: urn:taxii.mitre.org:message:xml:1.0</taxii_11:Message>
</taxii_11:Status_Message>
```

So it took me some experimentation but I changed cti.py to use taxii 1.1

```

    poll_params = tm11.PollParameters(
        allow_asynch=False,
        response_type=RT_FULL,
        content_bindings=[tm11.ContentBinding(binding_id=CB_STIX_XML_11)])

    poll_request = tm11.PollRequest(
       message_id=tm11.generate_message_id(),
        collection_name=collection,
        exclusive_begin_timestamp_label=earliest,
        inclusive_end_timestamp_label=latest,
        poll_parameters=(poll_params) )

    http_response = client.callTaxiiService2(
        host, endpoint,
        t.VID_TAXII_XML_11, poll_request.to_xml(),
        port=port)
    taxii_message = t.get_message_from_http_response(http_response,
                                                     poll_request.message_id)

```

And this fixed that issue. (It introduced a new one but ill log that in a diff tracker)

**Comment by treyka** [comment]
@JasonKeirstead Thanks for the issue, I'll get on this pronto! ^_^

**Comment by treyka** [comment]
Appears to be fixed, closing the issue.
